// <auto-generated />
using System;
using GameModule.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameModule.Migrations
{
    [DbContext(typeof(GameModuleDbContext))]
    [Migration("20231225221223_TaskLocalizationNotNull")]
    partial class TaskLocalizationNotNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("GameModule")
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameModule.Entities.Human", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodLevelPercentage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThermalLevelPercentage")
                        .HasColumnType("int");

                    b.Property<int>("TribeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TribeId");

                    b.ToTable("Humans", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.HumanTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<int>("HumanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.Property<int>("TribeId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HumanId")
                        .IsUnique();

                    b.HasIndex("TribeId");

                    b.ToTable("HumanTasks", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.HumanTaskOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("datetime2");

                    b.Property<int>("TribeId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TribeId");

                    b.ToTable("HumanTaskOrders", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HumanId")
                        .HasColumnType("int");

                    b.Property<int>("PriorityPercentage")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HumanId");

                    b.ToTable("Jobs", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.MapTile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MapTiles", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.Tribe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tribes", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.TribeRelocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.Property<int>("TribeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TribeId")
                        .IsUnique();

                    b.ToTable("TribeRelocations", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.TribeStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PowerAndDurability")
                        .HasColumnType("int");

                    b.Property<int>("TribeId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TribeId");

                    b.ToTable("TribeStructures", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.WorldZoneParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AverageTemperature")
                        .HasColumnType("int");

                    b.Property<bool>("IsBlizzard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSnow")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWind")
                        .HasColumnType("bit");

                    b.Property<int>("Zone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorldZoneParameter", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.Human", b =>
                {
                    b.HasOne("GameModule.Entities.Tribe", "Tribe")
                        .WithMany("Humans")
                        .HasForeignKey("TribeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GameModule.Entities.ValueObjects.Localization", "Localization", b1 =>
                        {
                            b1.Property<int>("HumanId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("HumanId");

                            b1.ToTable("Humans", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("HumanId");
                        });

                    b.Navigation("Localization")
                        .IsRequired();

                    b.Navigation("Tribe");
                });

            modelBuilder.Entity("GameModule.Entities.HumanTask", b =>
                {
                    b.HasOne("GameModule.Entities.Human", "Human")
                        .WithOne("HumanTask")
                        .HasForeignKey("GameModule.Entities.HumanTask", "HumanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameModule.Entities.Tribe", "Tribe")
                        .WithMany("HumanTasks")
                        .HasForeignKey("TribeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.OwnsOne("GameModule.Entities.ValueObjects.Localization", "Localization", b1 =>
                        {
                            b1.Property<int>("HumanTaskId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("HumanTaskId");

                            b1.ToTable("HumanTasks", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("HumanTaskId");
                        });

                    b.Navigation("Human");

                    b.Navigation("Localization")
                        .IsRequired();

                    b.Navigation("Tribe");
                });

            modelBuilder.Entity("GameModule.Entities.HumanTaskOrder", b =>
                {
                    b.HasOne("GameModule.Entities.Tribe", "Tribe")
                        .WithMany("HumanTaskOrders")
                        .HasForeignKey("TribeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GameModule.Entities.ValueObjects.Localization", "Localization", b1 =>
                        {
                            b1.Property<int>("HumanTaskOrderId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("HumanTaskOrderId");

                            b1.ToTable("HumanTaskOrders", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("HumanTaskOrderId");
                        });

                    b.Navigation("Localization")
                        .IsRequired();

                    b.Navigation("Tribe");
                });

            modelBuilder.Entity("GameModule.Entities.Job", b =>
                {
                    b.HasOne("GameModule.Entities.Human", "Human")
                        .WithMany("Jobs")
                        .HasForeignKey("HumanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Human");
                });

            modelBuilder.Entity("GameModule.Entities.MapTile", b =>
                {
                    b.OwnsOne("GameModule.Entities.TileRecourse", "Food", b1 =>
                        {
                            b1.Property<int>("MapTileId")
                                .HasColumnType("int");

                            b1.Property<int>("ActualPoints")
                                .HasColumnType("int");

                            b1.Property<int>("MaxLimitPoints")
                                .HasColumnType("int");

                            b1.HasKey("MapTileId");

                            b1.ToTable("MapTiles", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("MapTileId");
                        });

                    b.OwnsOne("GameModule.Entities.ValueObjects.Localization", "Localization", b1 =>
                        {
                            b1.Property<int>("MapTileId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("MapTileId");

                            b1.ToTable("MapTiles", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("MapTileId");
                        });

                    b.OwnsOne("GameModule.Entities.TileRecourse", "Wood", b1 =>
                        {
                            b1.Property<int>("MapTileId")
                                .HasColumnType("int");

                            b1.Property<int>("ActualPoints")
                                .HasColumnType("int");

                            b1.Property<int>("MaxLimitPoints")
                                .HasColumnType("int");

                            b1.HasKey("MapTileId");

                            b1.ToTable("MapTiles", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("MapTileId");
                        });

                    b.Navigation("Food")
                        .IsRequired();

                    b.Navigation("Localization")
                        .IsRequired();

                    b.Navigation("Wood")
                        .IsRequired();
                });

            modelBuilder.Entity("GameModule.Entities.Tribe", b =>
                {
                    b.OwnsOne("GameModule.Entities.Resources", "Resources", b1 =>
                        {
                            b1.Property<int>("TribeId")
                                .HasColumnType("int");

                            b1.Property<int>("FreshFood")
                                .HasColumnType("int");

                            b1.Property<int>("Wood")
                                .HasColumnType("int");

                            b1.HasKey("TribeId");

                            b1.ToTable("Tribes", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("TribeId");
                        });

                    b.OwnsOne("GameModule.Entities.ValueObjects.Localization", "Localization", b1 =>
                        {
                            b1.Property<int>("TribeId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("TribeId");

                            b1.ToTable("Tribes", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("TribeId");
                        });

                    b.Navigation("Localization")
                        .IsRequired();

                    b.Navigation("Resources")
                        .IsRequired();
                });

            modelBuilder.Entity("GameModule.Entities.TribeRelocation", b =>
                {
                    b.HasOne("GameModule.Entities.Tribe", "Tribe")
                        .WithOne("TribeRelocation")
                        .HasForeignKey("GameModule.Entities.TribeRelocation", "TribeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GameModule.Entities.ValueObjects.Localization", "Destiny", b1 =>
                        {
                            b1.Property<int>("TribeRelocationId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("TribeRelocationId");

                            b1.ToTable("TribeRelocations", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("TribeRelocationId");
                        });

                    b.OwnsOne("GameModule.Entities.ValueObjects.Localization", "Start", b1 =>
                        {
                            b1.Property<int>("TribeRelocationId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("TribeRelocationId");

                            b1.ToTable("TribeRelocations", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("TribeRelocationId");
                        });

                    b.Navigation("Destiny")
                        .IsRequired();

                    b.Navigation("Start")
                        .IsRequired();

                    b.Navigation("Tribe");
                });

            modelBuilder.Entity("GameModule.Entities.TribeStructure", b =>
                {
                    b.HasOne("GameModule.Entities.Tribe", "Tribe")
                        .WithMany("TribeStructures")
                        .HasForeignKey("TribeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tribe");
                });

            modelBuilder.Entity("GameModule.Entities.Human", b =>
                {
                    b.Navigation("HumanTask");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("GameModule.Entities.Tribe", b =>
                {
                    b.Navigation("HumanTaskOrders");

                    b.Navigation("HumanTasks");

                    b.Navigation("Humans");

                    b.Navigation("TribeRelocation");

                    b.Navigation("TribeStructures");
                });
#pragma warning restore 612, 618
        }
    }
}
