// <auto-generated />
using System;
using GameModule.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameModule.Migrations
{
    [DbContext(typeof(GameModuleDbContext))]
    [Migration("20230911183510_RelocationOneToOne")]
    partial class RelocationOneToOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("GameModule")
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameModule.Entities.HumanUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodLevelPercentage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TribeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TribeId");

                    b.ToTable("HumanUnits", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.HumanUnitTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<int>("HumanUnitId")
                        .HasColumnType("int");

                    b.Property<int?>("MapTileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.Property<int>("TribeId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HumanUnitId");

                    b.HasIndex("TribeId");

                    b.ToTable("HumanUnitTasks", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.HumanUnitTaskOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsInProgress")
                        .HasColumnType("bit");

                    b.Property<int?>("MapTileId")
                        .HasColumnType("int");

                    b.Property<int>("TribeId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TribeId");

                    b.ToTable("HumanUnitTaskOrders", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.MapTile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MapTiles", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.Tribe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tribes", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.TribeRelocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.Property<int>("TribeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TribeId")
                        .IsUnique();

                    b.ToTable("TribeRelocations", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.HumanUnit", b =>
                {
                    b.HasOne("GameModule.Entities.Tribe", "Tribe")
                        .WithMany("HumanUnits")
                        .HasForeignKey("TribeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GameModule.Entities.ValueObjects.Localization", "Localization", b1 =>
                        {
                            b1.Property<int>("HumanUnitId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("HumanUnitId");

                            b1.ToTable("HumanUnits", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("HumanUnitId");
                        });

                    b.Navigation("Localization")
                        .IsRequired();

                    b.Navigation("Tribe");
                });

            modelBuilder.Entity("GameModule.Entities.HumanUnitTask", b =>
                {
                    b.HasOne("GameModule.Entities.HumanUnit", "HumanUnit")
                        .WithMany("HumanUnitTasks")
                        .HasForeignKey("HumanUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameModule.Entities.Tribe", null)
                        .WithMany("HumanUnitTasks")
                        .HasForeignKey("TribeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HumanUnit");
                });

            modelBuilder.Entity("GameModule.Entities.HumanUnitTaskOrder", b =>
                {
                    b.HasOne("GameModule.Entities.Tribe", "Tribe")
                        .WithMany("HumanUnitTaskOrders")
                        .HasForeignKey("TribeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tribe");
                });

            modelBuilder.Entity("GameModule.Entities.MapTile", b =>
                {
                    b.OwnsOne("GameModule.Entities.TileRecourse", "Food", b1 =>
                        {
                            b1.Property<int>("MapTileId")
                                .HasColumnType("int");

                            b1.Property<int>("ActualPoints")
                                .HasColumnType("int");

                            b1.Property<int>("MaxLimitPoints")
                                .HasColumnType("int");

                            b1.HasKey("MapTileId");

                            b1.ToTable("MapTiles", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("MapTileId");
                        });

                    b.OwnsOne("GameModule.Entities.ValueObjects.Localization", "Localization", b1 =>
                        {
                            b1.Property<int>("MapTileId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("MapTileId");

                            b1.ToTable("MapTiles", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("MapTileId");
                        });

                    b.OwnsOne("GameModule.Entities.TileRecourse", "Wood", b1 =>
                        {
                            b1.Property<int>("MapTileId")
                                .HasColumnType("int");

                            b1.Property<int>("ActualPoints")
                                .HasColumnType("int");

                            b1.Property<int>("MaxLimitPoints")
                                .HasColumnType("int");

                            b1.HasKey("MapTileId");

                            b1.ToTable("MapTiles", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("MapTileId");
                        });

                    b.Navigation("Food")
                        .IsRequired();

                    b.Navigation("Localization")
                        .IsRequired();

                    b.Navigation("Wood")
                        .IsRequired();
                });

            modelBuilder.Entity("GameModule.Entities.Tribe", b =>
                {
                    b.OwnsOne("GameModule.Entities.Resources", "Resources", b1 =>
                        {
                            b1.Property<int>("TribeId")
                                .HasColumnType("int");

                            b1.Property<int>("FreshFood")
                                .HasColumnType("int");

                            b1.Property<int>("Wood")
                                .HasColumnType("int");

                            b1.HasKey("TribeId");

                            b1.ToTable("Tribes", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("TribeId");
                        });

                    b.OwnsOne("GameModule.Entities.ValueObjects.Localization", "Localization", b1 =>
                        {
                            b1.Property<int>("TribeId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("TribeId");

                            b1.ToTable("Tribes", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("TribeId");
                        });

                    b.Navigation("Localization")
                        .IsRequired();

                    b.Navigation("Resources")
                        .IsRequired();
                });

            modelBuilder.Entity("GameModule.Entities.TribeRelocation", b =>
                {
                    b.HasOne("GameModule.Entities.Tribe", "Tribe")
                        .WithOne("TribeRelocation")
                        .HasForeignKey("GameModule.Entities.TribeRelocation", "TribeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GameModule.Entities.ValueObjects.Localization", "Destiny", b1 =>
                        {
                            b1.Property<int>("TribeRelocationId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("TribeRelocationId");

                            b1.ToTable("TribeRelocations", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("TribeRelocationId");
                        });

                    b.OwnsOne("GameModule.Entities.ValueObjects.Localization", "Start", b1 =>
                        {
                            b1.Property<int>("TribeRelocationId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("TribeRelocationId");

                            b1.ToTable("TribeRelocations", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("TribeRelocationId");
                        });

                    b.Navigation("Destiny")
                        .IsRequired();

                    b.Navigation("Start")
                        .IsRequired();

                    b.Navigation("Tribe");
                });

            modelBuilder.Entity("GameModule.Entities.HumanUnit", b =>
                {
                    b.Navigation("HumanUnitTasks");
                });

            modelBuilder.Entity("GameModule.Entities.Tribe", b =>
                {
                    b.Navigation("HumanUnitTaskOrders");

                    b.Navigation("HumanUnitTasks");

                    b.Navigation("HumanUnits");

                    b.Navigation("TribeRelocation");
                });
#pragma warning restore 612, 618
        }
    }
}
