// <auto-generated />
using System;
using GameModule.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameModule.Migrations
{
    [DbContext(typeof(GameModuleDbContext))]
    [Migration("20230725202406_RenameNameToMapTiles")]
    partial class RenameNameToMapTiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("GameModule")
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameModule.Entities.HumanUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodLevelPercentage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TribeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TribeId");

                    b.ToTable("HumanUnits", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.MapTile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MapTiles", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.Tribe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tribes", "GameModule");
                });

            modelBuilder.Entity("GameModule.Entities.HumanUnit", b =>
                {
                    b.HasOne("GameModule.Entities.Tribe", "Tribe")
                        .WithMany()
                        .HasForeignKey("TribeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GameModule.Entities.ValueObjects.Localization", "Localization", b1 =>
                        {
                            b1.Property<int>("HumanUnitId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("HumanUnitId");

                            b1.ToTable("HumanUnits", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("HumanUnitId");
                        });

                    b.Navigation("Localization")
                        .IsRequired();

                    b.Navigation("Tribe");
                });

            modelBuilder.Entity("GameModule.Entities.MapTile", b =>
                {
                    b.OwnsOne("GameModule.Entities.TileRecourse", "Food", b1 =>
                        {
                            b1.Property<int>("MapTileId")
                                .HasColumnType("int");

                            b1.Property<int>("ActualPoints")
                                .HasColumnType("int");

                            b1.Property<int>("MaxLimitPoints")
                                .HasColumnType("int");

                            b1.HasKey("MapTileId");

                            b1.ToTable("MapTiles", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("MapTileId");
                        });

                    b.OwnsOne("GameModule.Entities.ValueObjects.Localization", "Localization", b1 =>
                        {
                            b1.Property<int>("MapTileId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("MapTileId");

                            b1.ToTable("MapTiles", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("MapTileId");
                        });

                    b.OwnsOne("GameModule.Entities.TileRecourse", "Wood", b1 =>
                        {
                            b1.Property<int>("MapTileId")
                                .HasColumnType("int");

                            b1.Property<int>("ActualPoints")
                                .HasColumnType("int");

                            b1.Property<int>("MaxLimitPoints")
                                .HasColumnType("int");

                            b1.HasKey("MapTileId");

                            b1.ToTable("MapTiles", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("MapTileId");
                        });

                    b.Navigation("Food")
                        .IsRequired();

                    b.Navigation("Localization")
                        .IsRequired();

                    b.Navigation("Wood")
                        .IsRequired();
                });

            modelBuilder.Entity("GameModule.Entities.Tribe", b =>
                {
                    b.OwnsOne("GameModule.Entities.ValueObjects.Localization", "Localization", b1 =>
                        {
                            b1.Property<int>("TribeId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("TribeId");

                            b1.ToTable("Tribes", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("TribeId");
                        });

                    b.Navigation("Localization")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
