// <auto-generated />
using GameModule.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameModule.Migrations
{
    [DbContext(typeof(GameModuleDbContext))]
    [Migration("20230626175042_InitForGameModule")]
    partial class InitForGameModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("GameModule")
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameModule.DataBaseModels.HumanUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodLevelPercentage")
                        .HasColumnType("int");

                    b.Property<int>("TribeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TribeId");

                    b.ToTable("HumanUnits", "GameModule");
                });

            modelBuilder.Entity("GameModule.DataBaseModels.Tribe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tribes", "GameModule");
                });

            modelBuilder.Entity("GameModule.DataBaseModels.HumanUnit", b =>
                {
                    b.HasOne("GameModule.DataBaseModels.Tribe", "Tribe")
                        .WithMany()
                        .HasForeignKey("TribeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GameModule.DataBaseModels.ValueObjects.Localization", "Localization", b1 =>
                        {
                            b1.Property<int>("HumanUnitId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("HumanUnitId");

                            b1.ToTable("HumanUnits", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("HumanUnitId");
                        });

                    b.Navigation("Localization")
                        .IsRequired();

                    b.Navigation("Tribe");
                });

            modelBuilder.Entity("GameModule.DataBaseModels.Tribe", b =>
                {
                    b.OwnsOne("GameModule.DataBaseModels.ValueObjects.Localization", "Localization", b1 =>
                        {
                            b1.Property<int>("TribeId")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("TribeId");

                            b1.ToTable("Tribes", "GameModule");

                            b1.WithOwner()
                                .HasForeignKey("TribeId");
                        });

                    b.Navigation("Localization")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
