// <auto-generated />
using System;
using AccountModule.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountModule.Migrations
{
    [DbContext(typeof(AccountModuleDbContext))]
    [Migration("20231016081923_InitDbV2")]
    partial class InitDbV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("AccountModule")
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountModule.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Accounts", "AccountModule");
                });

            modelBuilder.Entity("AccountModule.Entities.Account", b =>
                {
                    b.OwnsOne("AccountModule.Entities.ValueObject.GuestAccount", "GuestAccount", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("LastLoginDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ReLoginToken")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AccountId");

                            b1.ToTable("Accounts", "AccountModule");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.OwnsOne("AccountModule.Entities.ValueObject.RegisteredAccount", "RegisteredAccount", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AccountId");

                            b1.ToTable("Accounts", "AccountModule");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("GuestAccount");

                    b.Navigation("RegisteredAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
