<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="6.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\GameModule\GameModule.csproj" />
    <ProjectReference Include="..\..\NotificationModule\NotificationModule.csproj" />
    <ProjectReference Include="..\..\PlayerAccount\AccountModule.csproj" />
    <ProjectReference Include="..\Client\ProjectNomad.Client.csproj" />
    <ProjectReference Include="..\Shared\ProjectNomad.Shared.csproj" />
  </ItemGroup>


</Project>
